# Generated by Django 6.0.3 on 2026-03-25 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('navigation', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('heavy_rain', 'Heavy Rainfall'), ('flood', 'Flood Risk'), ('strong_wind', 'Strong Wind'), ('unsafe_trail', 'Unsafe Trail'), ('river_crossing', 'River Crossing Risk'), ('storm', 'Storm Warning')], max_length=30)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('danger', 'Danger'), ('extreme', 'Extreme')], default='warning', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_alerts', to='users.userprofile')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_alerts', to='navigation.trekkingroute')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WeatherReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(choices=[('clear', 'Clear'), ('cloudy', 'Cloudy'), ('rain', 'Rain'), ('heavy_rain', 'Heavy Rain'), ('storm', 'Storm'), ('flood_risk', 'Flood Risk'), ('strong_wind', 'Strong Wind'), ('fog', 'Fog')], max_length=20)),
                ('temperature_c', models.DecimalField(decimal_places=1, max_digits=5)),
                ('wind_speed_kph', models.DecimalField(decimal_places=1, max_digits=5)),
                ('rainfall_mm', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('humidity_pct', models.IntegerField(default=0)),
                ('is_safe_to_trek', models.BooleanField(default=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(blank=True, default='manual', max_length=100)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_reports', to='navigation.trekkingroute')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
