# Generated by Django 6.0.3 on 2026-03-25 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('navigation', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(choices=[('injury', 'Injury'), ('lost', 'Lost Trekker'), ('vehicle', 'Vehicle Incident'), ('weather', 'Weather Related'), ('wildlife', 'Wildlife Encounter'), ('other', 'Other')], max_length=20)),
                ('severity', models.CharField(choices=[('minor', 'Minor'), ('moderate', 'Moderate'), ('serious', 'Serious'), ('critical', 'Critical')], default='minor', max_length=10)),
                ('description', models.TextField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('occurred_at', models.DateTimeField()),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('involved_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents_involved', to='users.userprofile')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filed_incidents', to='users.userprofile')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='navigation.trekkingroute')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='TouristRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('inside', 'Inside Trek Area'), ('exited', 'Exited'), ('overdue', 'Overdue / Not Exited')], default='registered', max_length=15)),
                ('group_size', models.PositiveIntegerField(default=1)),
                ('planned_entry', models.DateTimeField()),
                ('planned_exit', models.DateTimeField()),
                ('actual_entry', models.DateTimeField(blank=True, null=True)),
                ('actual_exit', models.DateTimeField(blank=True, null=True)),
                ('permit_number', models.CharField(max_length=50, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='users.userprofile')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='navigation.trekkingroute')),
                ('session', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration', to='users.trekkingsession')),
            ],
            options={
                'ordering': ['-registered_at'],
            },
        ),
    ]
