# Generated by Django 6.0.3 on 2026-03-25 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrekkingRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='San Marcelino Mapanuepe', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('expert', 'Expert')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('caution', 'Caution')], default='open', max_length=10)),
                ('start_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('start_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('end_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('end_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('total_distance_km', models.DecimalField(decimal_places=2, max_digits=6)),
                ('estimated_hours', models.DecimalField(decimal_places=1, max_digits=4)),
                ('elevation_gain_m', models.IntegerField(default=0)),
                ('allowed_vehicles', models.CharField(default='motorcycle,4x4,suv,none', max_length=100)),
                ('offline_map_file', models.FileField(blank=True, null=True, upload_to='offline_maps/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Checkpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('cp_type', models.CharField(choices=[('waypoint', 'Waypoint'), ('camp', 'Camp Entrance'), ('river', 'River Crossing'), ('danger', 'Danger Zone'), ('rest', 'Rest Area'), ('emergency', 'Emergency Point')], default='waypoint', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('alert_message', models.CharField(blank=True, help_text='Alert shown when user is ~200m away', max_length=300)),
                ('radius_meters', models.IntegerField(default=200, help_text='Trigger radius in metres')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='navigation.trekkingroute')),
            ],
            options={
                'ordering': ['route', 'order'],
            },
        ),
    ]
