# Generated by Django 6.0.3 on 2026-03-25 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('navigation', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('message', models.TextField(blank=True, default='SOS — I need help!')),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('acknowledged', 'Acknowledged'), ('responding', 'Responding'), ('resolved', 'Resolved')], default='sent', max_length=15)),
                ('rescue_team_notified', models.BooleanField(default=False)),
                ('contacts_notified', models.BooleanField(default=False)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Rescue team notes')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sos_alerts', to='users.userprofile')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sos_alerts', to='users.trekkingsession')),
            ],
            options={
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleSafetyCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(max_length=20)),
                ('result', models.CharField(choices=[('approved', 'Approved'), ('caution', 'Proceed with Caution'), ('not_recommended', 'Not Recommended'), ('blocked', 'Blocked / Unsafe')], max_length=20)),
                ('alert_message', models.TextField()),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_checks', to='users.userprofile')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_checks', to='navigation.trekkingroute')),
            ],
            options={
                'ordering': ['-checked_at'],
            },
        ),
    ]
